[package]
name = "xworkflow-template-jinja"
version = "0.1.0"
edition = "2021"

[dependencies]
minijinja = { version = "2.0", features = ["builtins", "fuel"] }
serde_json = "1.0"

xworkflow-types = { path = "../xworkflow-types" }
